site_name: Github Documentation
nav:
  - Home: "index.md"
  - Issues: "issues.md"
  - Glossary: "glossary.md"
  - Troubleshooting: "troubleshooting.md"

repo_url: https://github.com/Wilbster/GitHub-Instructions

repo_name: Wilbster/GitHub-Instructions

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list

theme:
  name: material
  logo: assets/images/github.png
  
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
copyright: Copyright &copy; 2023 Justin & Wilber